version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    depends_on:
      - app

  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
